# Generated by Django 6.0.1 on 2026-09-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('borrower', 'Borrower'), ('staff', 'Staff')], default='borrower', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('ghl_contact_id', models.CharField(blank=True, default='', max_length=64)),
                ('ghl_location_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_profiles',
            },
        ),
    ]
