# Generated by Django 6.0.1 on 2026-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('application', 'Application'), ('processing', 'Processing'), ('underwriting', 'Underwriting'), ('approval', 'Approval'), ('closing', 'Closing'), ('funded', 'Funded')], default='application', max_length=20)),
                ('stage_name', models.CharField(blank=True, default='', max_length=255)),
                ('pipeline_name', models.CharField(blank=True, default='', max_length=255)),
                ('opportunity_name', models.CharField(blank=True, default='', max_length=255)),
                ('ghl_contact_id', models.CharField(blank=True, default='', max_length=64)),
                ('ghl_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
