# Generated by Django 6.0.1 on 2026-03-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GHLAuthCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('scope', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, default='America/Chicago', max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.CharField(blank=True, help_text='GHL parentId for media upload-file (e.g. folder/location ID)', max_length=100)),
                ('alt_type', models.CharField(default='location', help_text="For media update/delete API (e.g. 'location')", max_length=50)),
                ('alt_id', models.CharField(blank=True, help_text='For media update/delete API (e.g. location ID); leave blank to use location_id', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GHLCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Human-readable name of the custom field (e.g., 'Quote URL', 'Invoice URL')", max_length=255)),
                ('ghl_field_id', models.CharField(help_text='The GHL custom field ID used in API calls', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', help_text='Type of the custom field', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this field is used for', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom field mapping is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The account this custom field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'ghl_custom_fields',
                'ordering': ['field_name'],
                'indexes': [models.Index(fields=['account', 'is_active'], name='ghl_custom__account_bda223_idx'), models.Index(fields=['ghl_field_id'], name='ghl_custom__ghl_fie_036e1e_idx')],
                'unique_together': {('account', 'ghl_field_id')},
            },
        ),
    ]
