# Generated by Django 6.0.1 on 2026-01-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Assets, Credit, Entity)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Loan type name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the loan type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Print group name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the print group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name (e.g., Bank Statements, Gift Letter)', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of what the document is and its purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.category')),
                ('loan_types', models.ManyToManyField(blank=True, help_text='Loan types that require this document', related_name='documents', to='documents.loantype')),
                ('print_groups', models.ManyToManyField(blank=True, help_text='Print groups this document belongs to', related_name='documents', to='documents.printgroup')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='documents_d_name_6c07ba_idx'), models.Index(fields=['category'], name='documents_d_categor_fec314_idx')],
            },
        ),
    ]
