# Generated by Django 6.0.1 on 2026-01-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='loan_types',
        ),
        migrations.RemoveField(
            model_name='document',
            name='print_groups',
        ),
        migrations.DeleteModel(
            name='LoanType',
        ),
        migrations.AddField(
            model_name='document',
            name='loan_types',
            field=models.JSONField(blank=True, default=list, help_text="List of loan types that require this document (e.g., ['Conventional Refinance (W-2)', 'FHA Purchase (W-2)'])"),
        ),
        migrations.DeleteModel(
            name='PrintGroup',
        ),
        migrations.AddField(
            model_name='document',
            name='print_groups',
            field=models.JSONField(blank=True, default=list, help_text="List of print groups this document belongs to (e.g., ['Profit & Loss', 'Bank Statements'])"),
        ),
    ]
