# Generated by Django 6.0.1 on 2026-01-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_loan_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Print group name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the print group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='loan_types',
        ),
        migrations.RemoveField(
            model_name='document',
            name='print_groups',
        ),
        migrations.AddField(
            model_name='document',
            name='print_groups',
            field=models.ManyToManyField(blank=True, help_text='Print groups this document belongs to', related_name='documents', to='documents.printgroup'),
        ),
    ]
