# Generated by Django 6.0.1 on 2026-01-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_printgroup_remove_document_loan_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
