# Generated by Django 6.0.1 on 2026-01-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='Unique identifier from URL (e.g., gfgwgvffrffgggrg)', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminDocumentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('adhoc', 'AD HOC'), ('individual', 'Individual Documents'), ('needs_list', 'Needs List')], help_text='Type of section: adhoc, individual, or needs_list', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The document selected by admin', on_delete=django.db.models.deletion.CASCADE, related_name='admin_selections', to='documents.document')),
                ('print_group', models.ForeignKey(blank=True, help_text='Print group (only for needs_list section type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_selections', to='documents.printgroup')),
                ('request', models.ForeignKey(help_text='The document request this selection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='admin_selections', to='documents.documentrequest')),
            ],
            options={
                'ordering': ['section_type', 'created_at'],
                'unique_together': {('request', 'section_type', 'document', 'print_group')},
            },
        ),
        migrations.CreateModel(
            name='UserDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='User uploaded file (image, PDF, document, etc.)', upload_to='user_uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_selection', models.ForeignKey(help_text='The admin selection this upload belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_uploads', to='documents.admindocumentselection')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
