# Generated by Django 6.0.1 on 2026-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentrequest_admindocumentselection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentupload',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Whether the admin has accepted this document'),
        ),
        migrations.AddField(
            model_name='userdocumentupload',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the document was accepted by admin', null=True),
        ),
    ]
