# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_userdocumentupload_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentupload',
            name='ghl_file_id',
            field=models.CharField(blank=True, help_text='GHL media fileId from upload-file API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdocumentupload',
            name='ghl_file_url',
            field=models.URLField(blank=True, help_text='GHL media URL from upload-file API (use for viewing)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdocumentupload',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original file name for display', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocumentupload',
            name='file',
            field=models.FileField(blank=True, help_text='Legacy: file on server (prefer GHL URL)', null=True, upload_to='user_uploads/%Y/%m/%d/'),
        ),
    ]
