# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_userdocumentupload_ghl_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCardSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='Unique identifier from URL (same pattern as document request)', max_length=255, unique=True)),
                ('form_data', models.JSONField(default=dict, help_text='All form fields as key-value pairs (street, city, purpose, etc.)')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'verbose_name': 'Opportunity Card Submission',
                'verbose_name_plural': 'Opportunity Card Submissions',
            },
        ),
    ]
