# Generated by Django 6.0.1 on 2026-02-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_opportunitycardsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='request',
            field=models.ForeignKey(blank=True, help_text='If set, this document is visible only for this request (custom ad hoc/individual/needs list doc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_documents', to='documents.documentrequest'),
        ),
    ]
