# Generated by Django 6.0.1 on 2026-02-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_add_document_request_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='printgroup',
            name='request',
            field=models.ForeignKey(blank=True, help_text='If set, this print group is visible only for this request (custom needs list group)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_print_groups', to='documents.documentrequest'),
        ),
        migrations.AlterField(
            model_name='printgroup',
            name='name',
            field=models.CharField(help_text='Print group name', max_length=200),
        ),
    ]
