# Generated by Django 6.0.1 on 2026-02-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_add_print_group_request_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='request',
            field=models.ForeignKey(blank=True, help_text='If set, this category is visible only for this request (custom ad hoc/individual/needs list category)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='documents.documentrequest'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Assets, Credit, Entity)', max_length=100),
        ),
    ]
