# Generated by Django 6.0.1 on 2026-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_add_category_request_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycardsubmission',
            name='ghl_note_id',
            field=models.CharField(blank=True, help_text='GHL contact note ID; when set, we do not create another note on resubmit', max_length=255, null=True),
        ),
    ]
