# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_opportunitycardsubmission_ghl_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='ghl_needs_list_note_id',
            field=models.CharField(
                blank=True,
                help_text='GHL contact note ID for the needs list; when set, we update this note on subsequent changes instead of creating a new one',
                max_length=255,
                null=True,
            ),
        ),
    ]
