# Generated by Django 6.0.1 on 2026-09-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_needslisttemplate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='needslisttemplate',
            new_name='documents_n_account_dd5b88_idx',
            old_name='documents_n_account_7c0f1a_idx',
        ),
    ]
