# Generated by Django 6.0.1 on 2026-09-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_attachment_mode_and_cleanup_needs_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(help_text='The loan program (category) this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Legacy local file (prefer blank_template / GHL)', null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='print_groups',
            field=models.ManyToManyField(blank=True, help_text='Legacy print groups (needs list); unused in new loan-program flow', related_name='documents', to='documents.printgroup'),
        ),
        migrations.AlterField(
            model_name='document',
            name='request',
            field=models.ForeignKey(blank=True, help_text='If set, this document is visible only for this request (custom doc)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_documents', to='documents.documentrequest'),
        ),
    ]
